version: '3.8'

services:
  front-end:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    container_name: front-end
    ports:
      - "5173:5173"
    volumes:
      - ./FRONTEND:/app/front-end

  # back-end:
  #   container_name: back-end
  #   build:
  #     context: ./BACKEND
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3333:3333"
  #   volumes:
  #     - ./BACKEND:/app/back-end
  #   depends_on:
  #     - db
  #   networks:
  #     - networkName

  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    
