version: "3.8"

services:
  front-end:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    container_name: front-end
    ports:
      - "5173:5173"
    volumes:
      - ./FRONTEND:/app/front-end
    networks:
      - app-network

  back-end:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    container_name: back-end
    ports:
      - "3333:3333"
      - "5555:5555"
    environment:
      - PRISMA_QUERY_ENGINE_TIMEOUT=60000
    volumes:
      - ./BACKEND:/app/back-end
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

